config/routes.rb
BasecampClone::Application.routes.draw do

  devise_scope :user do
    root :to => 'static#index'
  end

  devise_for :users
  resources :projects
  resources :lists
  resources :tasks
  resources :memberships

end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :description, :name, :project_id, :user_id
  belongs_to :user
  has_many :tasks

end

app/models/membership.rb
class Membership < ActiveRecord::Base
  attr_accessible :admin, :project_id, :user_id
  belongs_to :user
  belongs_to :project
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :access, :name, :user_id, :description

  has_many :memberships
  has_many :users, :through => :memberships
  has_many :lists

  validates_presence_of :name, :description


end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :body, :completed_at, :deleted_at, :due_date, :list_id, :user_id

  belongs_to :list
  belongs_to :user

  validates_presence_of :body
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :memberships
  has_many :projects, :through => :memberships
  has_many :lists
  has_many :tasks

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def new
    @project = Project.find(params[:project_id])
    @list = @project.lists.new
    respond_to do |format|
      format.js {render :action => 'new'}
    end
  end

  def create
    @list = List.new(params[:list])
    @project = Project.find(@list.project_id)
    respond_to do |format|
      if @list.save
        flash[:message] = "Good job creating a list."
        # redirect_to project_path(@list.project_id)
        format.js {render :action => 'restore'}
      else
        flash[:message] = "Bad job."
        render :new
      end
    end

  end

  def show
    @list = List.find(params[:id])
    @task = @list.tasks.new
  end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  def new
    @membership = Membership.new
    @project = Project.find(params[:id])
    respond_to do |format|
      format.js {render :action => 'new'}
    end
  end

  def create

    if @user = User.find_by_email(params[:membership][:user_id]) #actually, this is the email

      admin = false
      if params[:membership][:admin] == "1"
        admin = true
      end
      @membership  = @user.memberships.new
      @membership.admin = admin
      @membership.user_id = @user.id
      @membership.project_id = params[:membership][:project_id]

      if @membership.save
        flash[:success] = "You didn't screw up, jerk"

      else
        flash[:error] = "What are you doing?!"
      end

    else
      flash[:error] = "Enter valid email, dummy"
    end
    redirect_to :back

  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def new
    @user = current_user
    @project = @user.projects.new
  end

  def create
    @project = Project.new(params[:project])

    if @project.save
      flash[:message] = "Huzzah! Your project was created."
      @membership = @project.memberships.create(:user_id => current_user.id, :admin => true )
      redirect_to root_path#projects_path(:user_id => @project.user_id)
    else
      flash[:error] = "You screwed up big time, loser."
      render :new
    end
  end

  def index
    @user = User.find(params[:user_id])
    @memberships = @user.memberships.all
  end

  def show
    @project = Project.find(params[:id])
    @user = User.find(@project.user_id)
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def index
    render :layout => 'home'
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def new
    @list = List.find(params[:id])
    @task = @list.tasks.new
    respond_to do |format|
      format.js {render :action => 'new'}
    end
  end

  def create
    @task = Task.new(params[:task])
    @list = @task.list
    # @list = List.find(params[:task][:list_id])
    respond_to do |format|

      if @task.save
        flash[:success] = "More work created!"
        # redirect_to project_path(@task.list.project_id)
        format.js {render :action => 'restore'}
      else
        flash[:error] = "No go!"
        render 'list/show'
      end
    end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/common/_lists.html.erb
<%= list.name %>

app/views/layouts/_header.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <ul class="nav">
        <%= link_to "Basecamp Clone", root_path, class: "brand" %>
      </ul>

      <ul class="nav pull-right">
      <% if signed_in? %>
        <li class="dropdown">
          <a href="#"
                class="dropdown-toggle"
                data-toggle="dropdown">
                <%= current_user.email%>
                <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "My Projects", projects_path(:user_id => current_user.id)  %></li>
            <li><%= link_to "Add a Project", new_project_path  %></li>
            <li><%= link_to "Sign out", destroy_user_session_path, :method => "DELETE" %></li>
          </ul>
        </li>
      <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
      <% end %>
      </ul>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BasecampClone</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>


  <div class="container hero-unit">

    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <%= value %>
        <a class="close" data-dismiss="alert">&#215;</a>
      </div>
    <% end %>

    <%= yield %>

  </div>
</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Home</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>


  <div class="container hero-unit">

    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <%= value %>
        <a class="close" data-dismiss="alert">&#215;</a>
      </div>
    <% end %>

    <%= yield %>

  </div>
</body>
</html>

app/views/lists/_lists.html.erb
<% project.lists.each do |list| %>

  <p><%= link_to "#{list.name}", list_path(:id => list.id) %> - <%= list.description %></p>
  <ul class=<%="tasks-#{list.id}"%>>
    <%= render :partial => 'tasks/tasks', :locals => {:list => list}%>
  </ul>

  <div class =<%="new-task-#{list.id}"%>></div>
  <%= link_to "(+) Task", new_task_path(:id => list.id), :remote => true, class: "new-task-button" %>

<% end %>

app/views/lists/_new.html.erb
<%= form_for @list, :remote => true do |f| %>
 <p>
   List Name:<br>
   <%= f.text_field :name, :class => "span4" %>
 </p>
 <p>
   List Description:<br>
   <%= f.text_area :description, :class => "span8", :rows => 5 %>
 </p>
 <%= f.hidden_field :project_id %>
 <%= f.hidden_field :user_id, :value => @project.user_id %>


   <%= f.submit "Create List" , class: "btn btn-primary btn-medium" %>


 <% end %>

app/views/lists/new.html.erb
<p>Project: <%= @project.name %></p>
<p>Description: <%= @project.description %></p><br />


<%= form_for @list do |f| %>
 <p>
   List Name:<br>
   <%= f.text_field :name, :class => "span4" %>
 </p>
 <p>
   List Description:<br>
   <%= f.text_area :description, :class => "span8", :rows => 5 %>
 </p>
 <%= f.hidden_field :project_id %>
 <%= f.hidden_field :user_id, :value => @project.user_id %>


   <%= f.submit "Create List" , class: "btn btn-primary btn-medium" %>


 <% end %>

app/views/lists/new.js.erb
$('.new-list').html(
    "<%=j render(:partial => 'lists/new', :locals => {:list => @list})%>"
    );

$('.new-list-button').html(
    ''
);

app/views/lists/restore.js.erb
$('.new-list').html(
    ''
    );

$('.new-list-button').html(
    '(+) Task List'
);

$('.lists').html(
    '<%=j render :partial => "lists/lists", :locals => {:project => @project} %>'
    );

app/views/lists/show.html.erb
<%= @list.name %>

<%= render :partial =>'tasks/form' %>


<% @list.tasks.each do |task| %>
   <p><%= "#{task.body}" %></p>
<% end %>

app/views/memberships/_new.html.erb
<%= form_for @membership do |f| %>
  <br />
  <p>
    Admin:
    <%= f.check_box :admin %><br />
  </p>
  <p>
    Email:
    <%= f.text_field :user_id, :as => :email %><br />
    <%= f.hidden_field :project_id, :value => @project.id %>
  </p>
  <%= f.submit 'Add Member', :class => 'btn btn-small btn-primary' %>

<% end %>

app/views/memberships/new.js.erb
$('.membership').html(
    "<%=j render(:partial => 'memberships/new', :locals => {:membership => @membership})%>"
    );

$('.member-button').html(
    ''
);

app/views/projects/index.html.erb
<%= @user.email %>

<% @memberships.each do |membership| %>
  <% project = Project.find(membership.project_id)%>
  <p>
    <%= link_to project.name, project_path(project) %> -
    <%= project.description %>
    <% if membership.admin == true %>
       - (admin)
    <% else %>
       - (member)
    <% end %>
  </p>
<% end %>

app/views/projects/new.html.erb
<div class="hero-unit">
  <%= @user.email %><br /><br />
  <%= form_for @project do |f| %>
  <p>
    Project Name:<br>
    <%= f.text_field :name, :class => "span4" %>
  </p>
  <p>
    Public: <%= f.radio_button :access, "public", :checked => true %>
  </p>
  <p>
    Private: <%= f.radio_button :access, "private"%>
  </p>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <p>
    Project Description:<br>
    <%= f.text_area :description, :class => "span8", :rows => 5 %>
  </p>
    <%= f.submit "Create Project", class: "btn btn-primary btn-medium" %>


  <% end %>
</div>

app/views/projects/show.html.erb
Owner: <%= @user.email %><br />
Project: <%= @project.name %><br />
Project Description: <%= @project.description %><br />
access: <%= @project.access %><br />
members: <br /><% @project.memberships.each do |membership| %>
  <%= membership.user.email %><br />
<% end %>
<%= link_to "(+) Add Member", new_membership_path(:id => @project.id), :remote => true, class: "member-button" %>
<div class="membership"></div>

<br />
<%= link_to "(+) Task List", new_list_path(:project_id => @project), :remote => true, class: "new-list-button" %>
<div class ="new-list"></div>

<div class="lists">
  <%= render :partial => "lists/lists", :locals => {:project => @project} %>
</div>

app/views/tasks/_form.html.erb
<%= form_for @task, :remote => true do |f| %>
<p>
  Description:<br />
  <%= f.text_field :body %>
  </p>
  <p>
  Due Date:<br />
  <%= f.date_select(:due_date)%>

  <%= f.hidden_field(:list_id) %>
  <%= f.hidden_field :user_id, :value => current_user.id %>

  </p>

  <%= f.submit "Create Task", class: "btn btn-small btn-primary" %>

<% end %>

app/views/tasks/_tasks.html.erb
<% list.tasks.each do |task| %>
  <li><%= "#{task.body} due:#{task.due_date.strftime("%b %d, %Y")}" %></li>
<% end %>

app/views/tasks/new.js.erb
$('<%=".new-task-#{@list.id}"%>').html(
    "<%=j render(:partial => 'tasks/form', :locals => {:task => @task})%>"
    );

$('.new-task-button').html(
    ''
);

app/views/tasks/restore.js.erb
$('<%=".new-task-#{@list.id}"%>').html(
    ''
    );

$('.new-task-button').html(
    '(+) Task'
);

$('<%= "ul.tasks-#{@list.id}"%>').html(
    '<%=j render :partial => "tasks/tasks", :locals => {:list => @list} %>'
    );

app/views/users/show.html.erb
<%= link_to "sign out", destroy_user_session_path, :method => 'DELETE' %>

<%= @user.email %>